name: ScrubCustomItems
version: 1.0
api-version: 1.20
author: Regular Ben
main: main.ca.techgarage.ScrubCustomItems.Main
description: Created to serve Custom Items to the ScrubCraft server join the server @ scrubcraft.ca

commands:
    hello:
      aliases: [hi]
      description: Testing Hello Command
    spawnpaper:
      description: "Gives the Player a Spawn Teleport Paper"
      usage: "/spawnpaper"
      aliases: [sppaper, sp]
      permission: sc.customitems.give
      permission-message: "You do not have permission to use this command!"
    edgestone:
      description: "Gives the Player Edgestone"
      usage: "/edgestone"
      aliases: [estone, es]
      permission: sc.customitems.give
      permission-message: "You do not have permission to use this command!"
    serverheart:
      description: "Gives the Player a Server Heart"
      usage: "/serverheart"
      aliases: [sh, sheart]
      permission: sc.customitems.give
      permission-message: "You do not have permission to use this command!"
    blooddust:
      description: "Gives the Player a piece of Blood Dust"
      usage: "/blooddust"
      aliases: [bd, bdust]
      permission: sc.customitems.give
      permission-message: "You do not have permission to use this command!"
    teleportsword:
      description: "Gives the Player a Teleport Sword"
      usage: "/teleportsword"
      aliases: [tpsw, tpsword]
      permission: sc.customitems.give
      permission-message: "You do not have permission to use this command!"
    setSpawnPoint:
      description: Sets the teleport point for the Spawn Paper
      usage: /setSpawnPoint
      permission: sc.customitems.setspawnpoint
      permission-message: "You do not have permission to use this command!"
